# Change these first
owner: jocono-app # Your GitHub organization or username, where this repository lives
repo: jocono-status # The name of this repository

sites:
  - name: Jocono Landing
    url: https://www.jocono.de
  - name: Jocono Web App
    url: https://app.jocono.de
  - name: Jocono Web Beta App
    url: https://app.beta.jocono.de
  - name: Jocono Backend
    url: https://darlingproperty.backendless.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jocono.de
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/116795436?v=4
  name: Jocono Status
  introTitle:  ""
  introMessage: "" 
  favicon: https://status.jocono.de/assets/favicon-96x96.png
  theme: light
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  skipDescriptionUpdate: true
  skipTopicsUpdate: true
  skipHomepageUpdate: true
  navbar:
    - title: Home
      href: /
    - title: Landing
      href: https://jocono.de
    - title: App
      href: https://app.jocono.de
    - title: Beta
      href: https://app.beta.jocono.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
